### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidMatchBinding' of undefined

### ISSUE THREAD

**Issue by wtaysom** [batjko/key-peek#5]
**I have a fix.**

1. Just try toggling Key Peek in latest Atom.
2. The fix is to pluralize `keymap` to `keymaps`.  Must be an API change.

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [key-peek](https://github.com/batjko/key-peek) package, v0.2.6

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidMatchBinding' of undefined

```
At /Users/wtaysom/.atom/packages/key-peek/lib/key-peek-view.coffee:33

TypeError: Cannot read property 'onDidMatchBinding' of undefined
    at KeyPeekView.module.exports.KeyPeekView.attach (/Users/wtaysom/.atom/packages/key-peek/lib/key-peek-view.coffee:67:46)
    at KeyPeekView.module.exports.KeyPeekView.toggle (/Users/wtaysom/.atom/packages/key-peek/lib/key-peek-view.coffee:52:21)
    at atom-workspace.atom.commands.add.key-peek:toggle (/Users/wtaysom/.atom/packages/key-peek/lib/key-peek.coffee:13:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```

### Commands

```
     -0:00.5.0 key-peek:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "language-haskell",
      "neon-cursor",
      "neon-selection",
      "rainbow-selection"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.4
key-peek, v0.2.6
minimap, v4.10.0
minimap-selection, v4.2.0
tabular, v0.1.0

# Dev
No dev packages
```

**Comment by laughedelic** [comment]
I have the same bug. But I don't get what you mean by 

> pluralize `keymap` to `keymaps`

**Comment by batjko** [comment]
Sorry for the late reply. 
I agree, probably an API change. I'll publish a patch shortly...

**Comment by batjko** [comment]
0.2.7 has just been published. Let me know if you get any other issues.

And thanks for reporting the problem.

**Comment by wtaysom** [comment]
Oh I just mean that the API change was from atom.keymap to atom.keymaps.

**Comment by batjko** [comment]
Yes, that's how I understood it. So I changed my code to use the correct API call (`atom.keymaps`) instead and published a patch for it.

**Comment by laughedelic** [comment]
It seems to work fine now. Thanks :+1:
